"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import styles from "./RootLayout.module.css";
import Cart from "@/components/Cart/Cart";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cartOepn, setCartOpen] = useState(false);
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.main}>
          <Header cartOepn={cartOepn} setCartOepn={setCartOpen} />
          <div className={styles.content}>{children}</div>
          <Footer />
          <Cart open={cartOepn} setOpen={setCartOpen} />
        </div>
      </body>
    </html>
  );
}
